=== IvanaTesanovic/XMLBezbednostProjekat/xmlbsep31/src/main/resources/Schemas/Akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.skupstinans.rs"
    xmlns:pro="http://parlament.gov.rs/propisi" targetNamespace="http://www.skupstinans.rs"
    elementFormDefault="qualified" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:attribute name="Naziv" type="xs:string"/>
    <xs:attribute name="Opis" type="xs:string"/>
    <xs:element name="Zakon">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Deo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Glava">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="1"
                                            name="Odeljak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  ref="Clan"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="Pododeljak">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="1"
                                                  ref="Clan"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="ID"/>
                                                  <xs:attribute ref="Naziv"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute ref="Naziv"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Opis" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="ID"/>
                                    <xs:attribute ref="Naziv"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ID"/>
                        <xs:attribute name="RedniBroj" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ID"/>
            <xs:attribute ref="Naziv"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan" abstract="false">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded">
                <xs:element name="Ref"/>
                <xs:element name="Stav">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element maxOccurs="unbounded" minOccurs="2" name="Tacka">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element maxOccurs="unbounded" minOccurs="2"
                                            name="Podtacka">
                                            <xs:complexType>
                                                <xs:choice maxOccurs="unbounded">
                                                  <xs:element maxOccurs="unbounded" minOccurs="2"
                                                  name="Alineja">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="Tekst"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="ID"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="Tekst"/>
                                                </xs:choice>
                                                <xs:attribute name="ID"/>
                                                <xs:attribute ref="Naziv"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Tekst"/>
                                    </xs:choice>
                                    <xs:attribute name="ID"/>
                                    <xs:attribute ref="Naziv"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Tekst"/>
                        </xs:choice>
                        <xs:attribute name="ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="ID"/>
            <xs:attribute ref="Naziv"/>
            <xs:attribute ref="Opis"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IvanaTesanovic/XMLBezbednostProjekat/xmlbsep31/transform/noviValidanAkt.xml
<?xml  version="1.0" encoding="UTF-8"?>
<Zakon ID="222" ww:Naziv="Novi validan zakon" xsi:schemaLocation="http://www.skupstinans.rs file:/C:/Users/Ivana/Desktop/XML%26BSEP/xsd-ovi%20nasi/Akt.xsd" xmlns="http://www.skupstinans.rs" xmlns:ww="http://www.skupstinans.rs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Datum>2001-10-26T21:32:52
    </Datum>
    <Deo>
        <Glava>
            <Odeljak ID="0">
                <Pododeljak ww:Naziv="Pododeljak 2123">
                    <Clan ID="0">
                        <Stav ID="0" ww:Naziv="Stav 0">
                            <Tacka ID="0" ww:Naziv="Tacka 0">
                                <Podtacka ID="0">
                                    <Alineja ID="0" ww:Naziv="Naziv alineje">
                                        <Tekst>
                                            <Sadrzaj>Neki sadrzaj alineje.</Sadrzaj>
                                        </Tekst>
                                    </Alineja>
                                </Podtacka>
                            </Tacka>
                            <Tacka ID="1">
                                <Tekst>
                                    <Sadrzaj>Sadrzaj druge tacke.</Sadrzaj>
                                </Tekst>
                            </Tacka>
                        </Stav>
                    </Clan>
                    <Clan ID="1">
                        <Stav ID="2">
                            <Tekst>
                                <Sadrzaj>Sadrzaj stava drugog clana prvog.</Sadrzaj>
                            </Tekst>
                        </Stav>
                    </Clan>
                </Pododeljak>
            </Odeljak>
        </Glava>
    </Deo>
</Zakon>
